name: Build KernelSU Next LC
on:
  workflow_dispatch:
    inputs:
      CPU:
        description: "分支"
        required: true
        default: 'sm8650'
      FEIL:
        description: "配置文件"
        required: true
        default: 'oneplus12_v'
      CPUD:
        description: "处理器代号"
        required: true
        default: 'pineapple'
      ANDROID_VERSION:
        description: "内核安卓版本"
        required: true
        default: 'android14'
      KERNEL_VERSION:
        description: "内核版本"
        required: true
        default: '6.1'
      BUILD_METHOD:
        description: "编译方式"
        required: true
        default: 'gki'
      KSUNEXT_ENABLED:
        description: "添加 KSU Next"
        required: true
        type: boolean
        default: true
      SUSFS_ENABLED:
        description: "添加 SUSFS"
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 9216
          swap-reserve-mb: 4096
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Configure Git
        run: |
          git config --global user.name "CI Builder"
          git config --global user.email "builder@kernel.ci"
          git config --global core.fileMode false
          git config --global core.autocrlf input

      - name: Install dependencies
        run: |
          sudo apt update && sudo DEBIAN_FRONTEND=noninteractive apt upgrade -y
          sudo apt install -y \
            python3 git curl rsync \
            flex bison build-essential \
            libssl-dev libelf-dev bc

      - name: Setup repo tool
        run: |
          curl -s https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod +x ~/repo
          sudo mv ~/repo /usr/local/bin/

      - name: Initialize kernel source
        run: |
          mkdir -p kernel_workspace
          cd kernel_workspace
          repo init -u https://github.com/MClengchuan/oneplus_kernel_manifest.git \
            -b oneplus/${{ inputs.CPU }} \
            -m ${{ inputs.FEIL }}.xml \
            --depth=1 \
            --no-repo-verify
          repo sync -c -j$(nproc) --force-sync --no-clone-bundle

      - name: Clean source tree
        run: |
          cd kernel_workspace
          find . -name "abi_gki_protected_exports_*" -delete
          sed -i 's/ -dirty//g' kernel_platform/*/scripts/setlocalversion

      - name: Integrate KernelSU Next
        if: ${{ inputs.KSUNEXT_ENABLED }}
        run: |
          cd kernel_workspace/kernel_platform
          curl -fsSL "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | \
            bash -s -- next-susfs --force

          # Dynamic versioning
          cd KernelSU-Next
          KSU_VER=$(git describe --tags --always | sed 's/^v//;s/-/./g')
          echo
